import { date } from 'quasar';

const travelsTableHead = [
  {
    name: 'object',
    label: 'Имя объекта',
    field: 'object',
    align: 'left',
    sortable: true,
    headerStyle: 'width: 13%',
  },
  {
    name: 'startDate',
    label: 'Начало',
    field: 'p_start',
    format: (val) => `${date.formatDate(val, 'DD.MM.YYYY HH:MM')}`,
    align: 'center',
    sortable: true,
    headerStyle: 'width: 10%',
  },
  {
    name: 'endDate',
    label: 'Конец',
    field: 'p_end',
    format: (val) => `${date.formatDate(val, 'DD.MM.YYYY HH:MM')}`,
    align: 'center',
    sortable: true,
    headerStyle: 'width: 10%',
  },
  {
    name: 'millageP',
    label: 'Пробег (ПЛ)',
    field: 'millage_p',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 5%',
  },
  {
    name: 'millageW',
    label: 'Пробег (СМТ)',
    field: 'millage_w',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 5%',
  },
  {
    name: 'fupP',
    label: 'Заправка (ПЛ)',
    field: 'fuel_up_check',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 8%',
  },
  {
    name: 'fupW',
    label: 'Заправка (СМТ)',
    field: 'fuel_up_w',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 4%',
  },
  {
    name: 'fupStatus',
    label: 'Статус заправки',
    field: 'status_fuel_up',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 4%',
  },
  {
    name: 'fdown',
    label: 'Слито',
    field: 'fuel_down',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 4%',
  },
  {
    name: 'consumP',
    label: 'Расход (ПЛ)',
    field: 'consum_n',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 4%',
  },
  {
    name: 'consumF',
    label: 'Расход (Факт)',
    field: 'consum_f',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 4%',
  },
  {
    name: 'status',
    label: 'Результат',
    field: 'status',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 4%',
  },
];

export default { travelsTableHead };
