import { date } from 'quasar';

const fuelTransTableHead = [
  {
    name: 'date',
    label: 'Дата',
    field: 'date',
    format: (val) => `${date.formatDate(val, 'DD.MM.YYYY HH:MM')}`,
    align: 'center',
    sortable: true,
    headerStyle: 'width: 7%',
  },
  {
    name: 'card',
    label: 'Номер карты',
    field: 'card',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 10%',
  },
  {
    name: 'object',
    label: 'Объект транзакции',
    field: 'car',
    align: 'left',
    sortable: true,
    headerStyle: 'width: 15%',
  },
  {
    name: 'recVol',
    label: 'Литров',
    field: 'trans_up',
    format: (val) => `${val} л.`,
    align: 'center',
    sortable: true,
    headerStyle: 'width: 5%',
  },
  {
    name: 'wialonVol',
    label: 'Wialon',
    field: 'wialon_up',
    format: (val) => `${val} л.`,
    align: 'center',
    sortable: true,
    headerStyle: 'width: 5%',
  },
  {
    name: 'diff',
    label: 'Разница',
    field: 'dif_fuel',
    format: (val) => `${val} %`,
    align: 'center',
    sortable: true,
    headerStyle: 'width: 5%',
  },
  {
    name: 'percent',
    label: '%',
    field: 'dif_fuel_perc',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 5%',
  },
  {
    name: 'permError',
    label: 'Допуст. погр.',
    field: 'perms_fault',
    format: (val) => `${val} %`,
    align: 'center',
    sortable: true,
    headerStyle: 'width: 5%',
  },
  {
    name: 'registration',
    label: 'Регистрация',
    field: 'registration',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 6%',
  },
  {
    name: 'check',
    label: 'Проверка',
    field: 'result',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 9%',
  },
  {
    name: 'vendor',
    label: 'Поставщик',
    field: 'service',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 7%',
  },
  {
    name: 'cost',
    label: 'Стоимость кон.',
    field: 'discount_cost',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 7%',
  },
  {
    name: 'company',
    label: 'Компания',
    field: 'company',
    align: 'left',
    sortable: true,
    headerStyle: 'width: 14%',
  },
];

export default { fuelTransTableHead };
