import { date } from 'quasar';

const hrModuleTableHead = [
  {
    name: 'icon',
    align: 'center',
    headerStyle: 'width: 3%',
  },
  {
    name: 'lastName',
    align: 'left',
    label: 'Фамилия',
    field: 'last_name',
    sortable: true,
    headerStyle: 'width: 5%',
    classes: 'table__col-reduct',
  },
  {
    name: 'firstName',
    align: 'left',
    label: 'Имя',
    field: 'first_name',
    sortable: true,
    headerStyle: 'width: 5%',
    classes: 'table__col-reduct',
  },
  {
    name: 'secondName',
    align: 'left',
    label: 'Отчество',
    field: 'second_name',
    sortable: true,
    headerStyle: 'width: 6%',
    classes: 'table__col-reduct',
  },
  {
    name: 'position',
    align: 'left',
    label: 'Должность',
    field: 'position',
    sortable: true,
    headerStyle: 'width: 7%',
    classes: 'table__col-reduct',
  },
  {
    name: 'department',
    align: 'left',
    label: 'Подразделение',
    field: 'department',
    sortable: true,
    headerStyle: 'width: 8%',
    classes: 'table__col-reduct',
  },
  {
    name: 'personalPhone',
    align: 'center',
    label: 'Телефон',
    field: 'personal_phone',
    sortable: true,
    headerStyle: 'width: 6%',
    classes: 'table__col-reduct',
  },
  {
    name: 'workPhone',
    align: 'center',
    label: 'Раб. телефон',
    field: 'work_phone',
    sortable: true,
    headerStyle: 'width: 6%',
    classes: 'table__col-reduct',
  },
  {
    name: 'eMail',
    align: 'center',
    label: 'E-mail',
    field: 'e_mail',
    sortable: true,
    headerStyle: 'width: 8%',
    classes: 'table__col-reduct',
  },
  {
    name: 'register',
    align: 'center',
    label: 'Принят',
    field: 'register',
    sortable: true,
    format: (val) => `${date.formatDate(val, 'DD.MM.YYYY')}`,
    headerStyle: 'width: 6%',
    classes: 'table__col-reduct',
  },
  {
    name: 'city',
    align: 'center',
    label: 'Город',
    field: 'city',
    sortable: true,
    headerStyle: 'width: 5%',
    classes: 'table__col-reduct',
  },
  {
    name: 'persAddress',
    align: 'center',
    label: 'Адрес проживания',
    field: 'pers_address',
    sortable: true,
    headerStyle: 'width: 5%',
    headerClasses: 'table__col-wrap',
    classes: 'table__col-reduct',
  },
  {
    name: 'ofAddress',
    align: 'center',
    label: 'Адрес офиса',
    field: 'of_address',
    sortable: true,
    headerStyle: 'width: 6%',
    classes: 'table__col-reduct',
  },
  {
    name: 'status',
    align: 'center',
    label: 'Тип ТО',
    field: 'status',
    sortable: true,
    headerStyle: 'width: 8%',
    classes: 'table__col-reduct',
  },
  {
    name: 'statusPers',
    align: 'center',
    label: 'Статус',
    field: 'status_pers',
    sortable: true,
    headerStyle: 'width: 5%',
    classes: 'table__col-reduct',
  },
  {
    name: 'addContactFio',
    align: 'center',
    label: 'Доп. контакт',
    field: 'add_contact_fio',
    sortable: true,
    headerStyle: 'width: 5%',
    classes: 'table__col-reduct',
  },
  {
    name: 'addContactNum',
    align: 'center',
    label: 'Номер',
    field: 'add_contact_num',
    sortable: true,
    headerStyle: 'width: 5%',
    classes: 'table__col-reduct',
  },
];

export default { hrModuleTableHead };
