const userTableHead = [
  {
    name: 'userName',
    label: 'Пользователь',
    field: 'user',
    align: 'left',
    sortable: true,
    headerStyle: 'width: 14%',
  },
  {
    name: 'creator',
    label: 'Создатель',
    field: 'main_comp',
    format: (val) => (val ? `${val}` : 'Не указан'),
    align: 'left',
    sortable: true,
    headerStyle: 'width: 12%',
  },
  {
    name: 'tokenWialon',
    label: 'Token Wialon',
    field: 'main_token_wialon',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'email',
    label: 'E-mail',
    field: 'email',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'telegramID',
    label: 'ID Telegram',
    field: 'telegram_id',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessLc',
    label: 'Доступ к ЛК',
    field: 'lk',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessManager',
    label: 'Доступ к ЛК Менеджера',
    field: 'lk_manager',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessTechsupport',
    label: 'Доступ к ЛК Техпода',
    field: 'lk_techsup',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessLcHr',
    label: 'Доступ к ЛК HR',
    field: 'lk_hr',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessTravels',
    label: 'Доступ к Путевым',
    field: 'travels',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessFuelTrans',
    label: 'Доступ к Транзакциям',
    field: 'transacts',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessDiagnostic',
    label: 'Доступ к Диагностике',
    field: 'diagn',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'accessFuelDown',
    label: 'Доступ к Сливам',
    field: 'fdowns',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3',
  },
  {
    name: 'accessSalary',
    label: 'Доступ к Зарплате',
    field: 'acc_salary',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 3%',
  },
  {
    name: 'role',
    label: 'Роль',
    field: 'role',
    format: (val) => (val ? `${val}` : 'Не указана'),
    align: 'left',
    sortable: true,
    headerStyle: 'width: 10%',
  },
  {
    name: 'staff',
    label: 'Сотрудник Компании',
    field: 'staff_profile',
    format: (val) => (val ? `${val}` : 'Не указан'),
    align: 'left',
    sortable: true,
    headerStyle: 'width: 11%',
  },
  {
    name: 'location',
    label: 'Регион',
    field: 'location',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 11%',
  },
];

const slotsList = ['header-cell-tokenWialon', 'header-cell-email', 'header-cell-telegramID',
  'header-cell-accessLc', 'header-cell-accessManager', 'header-cell-accessTechsupport', 'header-cell-accessLcHr',
  'header-cell-accessTravels', 'header-cell-accessFuelTrans', 'header-cell-accessDiagnostic', 'header-cell-accessFuelDown',
  'header-cell-accessSalary', 'body-cell-tokenWialon', 'body-cell-email', 'body-cell-telegramID', 'body-cell-accessLc',
  'body-cell-accessManager', 'body-cell-accessTechsupport', 'body-cell-accessLcHr', 'body-cell-accessTravels', 'body-cell-accessFuelTrans',
  'body-cell-accessDiagnostic', 'body-cell-accessFuelDown', 'body-cell-accessSalary'];

const tableHeadSlots = [
  {
    cellName: 'tokenWialon',
    iconPath: 'img:icons/wialon.png',
    tooltipText: 'Token Wialon',
  },
  {
    cellName: 'email',
    iconPath: 'mdi-email-alert-outline',
    tooltipText: 'E-mail для уведомлений',
    color: 'blue-grey-7',
  },
  {
    cellName: 'telegramID',
    iconPath: 'img:icons/telegram.png',
    tooltipText: 'ID Telegram для уведомлений',
  },
  {
    cellName: 'accessLc',
    iconPath: 'mdi-chart-areaspline',
    tooltipText: 'Доступ к ЛК клиента',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessManager',
    iconPath: 'person',
    tooltipText: 'Доступ к ЛК менеджера',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessTechsupport',
    iconPath: 'manage_accounts',
    tooltipText: 'Доступ к ЛК тех.поддержки',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessLcHr',
    iconPath: 'groups',
    tooltipText: 'Доступ к ЛК HR',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessTravels',
    iconPath: 'fact_check',
    tooltipText: 'Доступ к Путевым',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessFuelTrans',
    iconPath: 'local_gas_station',
    tooltipText: 'Доступ к Транзакциям',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessDiagnostic',
    iconPath: 'car_crash',
    tooltipText: 'Доступ к Диагностике',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessFuelDown',
    iconPath: 'mdi-fuel',
    tooltipText: 'Доступ к Сливам',
    color: 'blue-grey-7',
  },
  {
    cellName: 'accessSalary',
    iconPath: 'payments',
    tooltipText: 'Доступ к Зарплате',
    color: 'blue-grey-7',
  },
];

const tableBodySlots = [
  { cellName: 'tokenWialon', field: 'main_token_wialon', tooltipText: 'Token Wialon не указан' },
  { cellName: 'email', field: 'email', tooltipText: 'E-mail для уведомлений не указан' },
  { cellName: 'telegramID', field: 'telegram_id', tooltipText: 'ID Telegram для уведомлений не указан' },
  { cellName: 'accessLc', field: 'lk', tooltipText: 'Нет доступа к ЛК Клиента' },
  { cellName: 'accessManager', field: 'lk_manager', tooltipText: 'Нет доступа к ЛК Менеджера' },
  { cellName: 'accessTechsupport', field: 'lk_techsup', tooltipText: 'Нет доступа к ЛК Техпода' },
  { cellName: 'accessLcHr', field: 'lk_hr', tooltipText: 'Нет доступа к ЛК HR' },
  { cellName: 'accessTravels', field: 'travels', tooltipText: 'Нет доступа к Путевым' },
  { cellName: 'accessFuelTrans', field: 'transacts', tooltipText: 'Нет доступа к Транзакциям' },
  { cellName: 'accessDiagnostic', field: 'diagn', tooltipText: 'Нет доступа к Диагностике' },
  { cellName: 'accessFuelDown', field: 'fdowns', tooltipText: 'Нет доступа к Сливам' },
  { cellName: 'accessSalary', field: 'acc_salary', tooltipText: 'Нет доступа к Зарплате' },
];

export default {
  userTableHead,
  slotsList,
  tableBodySlots,
  tableHeadSlots,
};
