const managerMainTableHead = [
  {
    name: 'company',
    label: 'Название компании',
    field: 'company_name',
    align: 'left',
    sortable: true,
    style: 'width: 13%',
  },
  {
    name: 'mainManager',
    label: 'основной',
    field: 'main_manager',
    align: 'center',
    sortable: true,
    style: 'width: 10%',
  },
  {
    name: 'servManager',
    label: 'сервисный',
    field: 'serv_manager',
    align: 'center',
    sortable: true,
    style: 'width: 10%',
  },
  {
    name: 'reqToCount',
    label: 'на ТО',
    field: 'req_to_count',
    align: 'center',
    sortable: true,
    style: 'width: 5%',
  },
  {
    name: 'reqTpCount',
    label: 'на ТП',
    field: 'req_tp_count',
    align: 'center',
    sortable: true,
    style: 'width: 5%',
  },
  {
    name: 'contractBalance',
    label: 'Баланс АП',
    field: 'balance_contract',
    align: 'center',
    sortable: true,
    style: 'width: 8%',
  },
  {
    name: 'travelCount',
    label: 'всего',
    field: 'travel_count',
    align: 'center',
    sortable: true,
    style: 'width: 4%',
  },
  {
    name: 'badTravelCount',
    label: 'проблем.',
    field: 'travel_fault_count',
    align: 'center',
    sortable: true,
    style: 'width: 4%',
  },
  {
    name: 'fuelTransCount',
    label: 'всего',
    field: 'trans_count',
    align: 'center',
    sortable: true,
    style: 'width: 4%',
  },
  {
    name: 'badFuelTransCount',
    label: 'погр.',
    field: 'trans_fault_count',
    align: 'center',
    sortable: true,
    style: 'width: 4%',
  },
  {
    name: 'fdownCount',
    label: 'всего',
    field: 'fd_count',
    align: 'center',
    sortable: true,
    style: 'width: 4%',
  },
  {
    name: 'badFdownCount',
    label: 'подтв.',
    field: 'fd_fault_count',
    align: 'center',
    sortable: true,
    style: 'width: 4%',
  },
  {
    name: 'statusSmt',
    label: 'Статус',
    field: 'status_smt',
    align: 'center',
    format: (val) => (val === true ? 'Активна' : 'Заблокирована'),
    sortable: true,
    style: 'width: 5%',
  },
  {
    name: 'commonBalance',
    label: 'Баланс (общий)',
    field: 'balance_common',
    align: 'center',
    sortable: true,
    style: 'width: 5%',
  },
  {
    name: 'story',
    label: 'История',
    align: 'center',
    sortable: true,
    style: 'width: 5%',
  },
];

export default { managerMainTableHead };
